goodFonts = [
    "AmericanTypewriter.ttc",
    "Andale Mono.ttf",
    "Arial Black.ttf",
    "Arial Bold Italic.ttf",
    "Arial Bold.ttf",
    "Arial Italic.ttf",
    "Arial Narrow Bold Italic.ttf",
    "Arial Narrow Bold.ttf",
    "Arial Narrow Italic.ttf",
    "Arial Narrow.ttf",
    "Arial Rounded Bold.ttf",
    "Arial Unicode.ttf",
    "Arial.ttf",
    "Baskerville.ttc",
    "BigCaslon.ttf",
    "Bodoni 72 OS.ttc",
    "Bodoni 72 Smallcaps Book.ttf",
    "Bodoni 72.ttc",
    "Bradley Hand Bold.ttf",
    "Brush Script.ttf",
    "Chalkboard.ttc",
    "ChalkboardSE.ttc",
    "Chalkduster.ttf",
    "Cochin.ttc",
    "Comic Sans MS Bold.ttf",
    "Comic Sans MS.ttf",
    "Copperplate.ttc",
    "Courier New Bold Italic.ttf",
    "Courier New Bold.ttf",
    "Courier New Italic.ttf",
    "Courier New.ttf",
    "Didot.ttc",
    "Futura.ttc",
    "Georgia Bold Italic.ttf",
    "Georgia Bold.ttf",
    "Georgia Italic.ttf",
    "Georgia.ttf",
    "GillSans.ttc",
    "Herculanum.ttf",
    "Hoefler Text.ttc",
    "Impact.ttf",
    "Luminari.ttf",
    "Microsoft Sans Serif.ttf",
    "Papyrus.ttc",
    "Phosphate.ttc",
    "Savoye LET.ttc",
    "SignPainter.ttc",
    "Skia.ttf",
    "SnellRoundhand.ttc",
    "STIXGeneral.otf",
    "STIXGeneralBol.otf",
    "STIXGeneralBolIta.otf",
    "STIXGeneralItalic.otf",
    "Tahoma Bold.ttf",
    "Tahoma.ttf",
    "Times New Roman Bold Italic.ttf",
    "Times New Roman Bold.ttf",
    "Times New Roman Italic.ttf",
    "Times New Roman.ttf",
    "Trattatello.ttf",
    "Trebuchet MS Bold Italic.ttf",
    "Trebuchet MS Bold.ttf",
    "Trebuchet MS Italic.ttf",
    "Trebuchet MS.ttf",
    "Verdana Bold Italic.ttf",
    "Verdana Bold.ttf",
    "Verdana Italic.ttf",
    "Verdana.ttf",
    "Zapfino.ttf",
    "Apple Symbols.ttf",
    "Avenir Next Condensed.ttc",
    "Avenir Next.ttc",
    "Avenir.ttc",
    "Courier.dfont",
    "Geneva.dfont",
    "Helvetica.ttc",
    "HelveticaNeue.ttc",
    "LucidaGrande.ttc",
    "MarkerFelt.ttc",
    "Menlo.ttc",
    "Monaco.dfont",
    "Noteworthy.ttc",
    "Optima.ttc",
    "Palatino.ttc",
    "Times.ttc",
]
